/*
Mezzanine API

Testing ShardsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mezzanine

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ryanbastic/go-mezzanine/pkg/mezzanine"
)

func Test_mezzanine_ShardsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShardsAPIService GetShardCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShardsAPI.GetShardCount(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
