/*
Mezzanine API

Testing CellsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mezzanine

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ryanbastic/go-mezzanine/pkg/mezzanine"
)

func Test_mezzanine_CellsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CellsAPIService GetCell", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rowKey string
		var columnName string
		var refKey int64

		resp, httpRes, err := apiClient.CellsAPI.GetCell(context.Background(), rowKey, columnName, refKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CellsAPIService GetCellLatest", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rowKey string
		var columnName string

		resp, httpRes, err := apiClient.CellsAPI.GetCellLatest(context.Background(), rowKey, columnName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CellsAPIService GetRow", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var rowKey string

		resp, httpRes, err := apiClient.CellsAPI.GetRow(context.Background(), rowKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CellsAPIService WriteCell", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CellsAPI.WriteCell(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
