/*
Mezzanine API

Testing IndexAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mezzanine

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ryanbastic/go-mezzanine/pkg/mezzanine"
)

func Test_mezzanine_IndexAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IndexAPIService QueryIndex", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var indexName string
		var shardKey string

		resp, httpRes, err := apiClient.IndexAPI.QueryIndex(context.Background(), indexName, shardKey).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
