/*
Mezzanine API

Sharded cell-based data store

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mezzanine

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WriteCellBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WriteCellBody{}

// WriteCellBody struct for WriteCellBody
type WriteCellBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Body interface{} `json:"body"`
	// Column name
	ColumnName string `json:"column_name"`
	// Reference key version
	RefKey int64 `json:"ref_key"`
	// Row key UUID
	RowKey string `json:"row_key"`
}

type _WriteCellBody WriteCellBody

// NewWriteCellBody instantiates a new WriteCellBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWriteCellBody(body interface{}, columnName string, refKey int64, rowKey string) *WriteCellBody {
	this := WriteCellBody{}
	this.Body = body
	this.ColumnName = columnName
	this.RefKey = refKey
	this.RowKey = rowKey
	return &this
}

// NewWriteCellBodyWithDefaults instantiates a new WriteCellBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWriteCellBodyWithDefaults() *WriteCellBody {
	this := WriteCellBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *WriteCellBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WriteCellBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *WriteCellBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *WriteCellBody) SetSchema(v string) {
	o.Schema = &v
}

// GetBody returns the Body field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *WriteCellBody) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WriteCellBody) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *WriteCellBody) SetBody(v interface{}) {
	o.Body = v
}

// GetColumnName returns the ColumnName field value
func (o *WriteCellBody) GetColumnName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ColumnName
}

// GetColumnNameOk returns a tuple with the ColumnName field value
// and a boolean to check if the value has been set.
func (o *WriteCellBody) GetColumnNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ColumnName, true
}

// SetColumnName sets field value
func (o *WriteCellBody) SetColumnName(v string) {
	o.ColumnName = v
}

// GetRefKey returns the RefKey field value
func (o *WriteCellBody) GetRefKey() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RefKey
}

// GetRefKeyOk returns a tuple with the RefKey field value
// and a boolean to check if the value has been set.
func (o *WriteCellBody) GetRefKeyOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefKey, true
}

// SetRefKey sets field value
func (o *WriteCellBody) SetRefKey(v int64) {
	o.RefKey = v
}

// GetRowKey returns the RowKey field value
func (o *WriteCellBody) GetRowKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RowKey
}

// GetRowKeyOk returns a tuple with the RowKey field value
// and a boolean to check if the value has been set.
func (o *WriteCellBody) GetRowKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowKey, true
}

// SetRowKey sets field value
func (o *WriteCellBody) SetRowKey(v string) {
	o.RowKey = v
}

func (o WriteCellBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WriteCellBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	toSerialize["column_name"] = o.ColumnName
	toSerialize["ref_key"] = o.RefKey
	toSerialize["row_key"] = o.RowKey
	return toSerialize, nil
}

func (o *WriteCellBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"body",
		"column_name",
		"ref_key",
		"row_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWriteCellBody := _WriteCellBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWriteCellBody)

	if err != nil {
		return err
	}

	*o = WriteCellBody(varWriteCellBody)

	return err
}

type NullableWriteCellBody struct {
	value *WriteCellBody
	isSet bool
}

func (v NullableWriteCellBody) Get() *WriteCellBody {
	return v.value
}

func (v *NullableWriteCellBody) Set(val *WriteCellBody) {
	v.value = val
	v.isSet = true
}

func (v NullableWriteCellBody) IsSet() bool {
	return v.isSet
}

func (v *NullableWriteCellBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWriteCellBody(val *WriteCellBody) *NullableWriteCellBody {
	return &NullableWriteCellBody{value: val, isSet: true}
}

func (v NullableWriteCellBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWriteCellBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


