/*
Mezzanine API

Sharded cell-based data store

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mezzanine

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RowResponse{}

// RowResponse struct for RowResponse
type RowResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Latest cell per column
	Cells []CellResponse `json:"cells"`
	// Row key UUID
	RowKey string `json:"row_key"`
}

type _RowResponse RowResponse

// NewRowResponse instantiates a new RowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRowResponse(cells []CellResponse, rowKey string) *RowResponse {
	this := RowResponse{}
	this.Cells = cells
	this.RowKey = rowKey
	return &this
}

// NewRowResponseWithDefaults instantiates a new RowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRowResponseWithDefaults() *RowResponse {
	this := RowResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *RowResponse) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RowResponse) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *RowResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *RowResponse) SetSchema(v string) {
	o.Schema = &v
}

// GetCells returns the Cells field value
// If the value is explicit nil, the zero value for []CellResponse will be returned
func (o *RowResponse) GetCells() []CellResponse {
	if o == nil {
		var ret []CellResponse
		return ret
	}

	return o.Cells
}

// GetCellsOk returns a tuple with the Cells field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RowResponse) GetCellsOk() ([]CellResponse, bool) {
	if o == nil || IsNil(o.Cells) {
		return nil, false
	}
	return o.Cells, true
}

// SetCells sets field value
func (o *RowResponse) SetCells(v []CellResponse) {
	o.Cells = v
}

// GetRowKey returns the RowKey field value
func (o *RowResponse) GetRowKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RowKey
}

// GetRowKeyOk returns a tuple with the RowKey field value
// and a boolean to check if the value has been set.
func (o *RowResponse) GetRowKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowKey, true
}

// SetRowKey sets field value
func (o *RowResponse) SetRowKey(v string) {
	o.RowKey = v
}

func (o RowResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Cells != nil {
		toSerialize["cells"] = o.Cells
	}
	toSerialize["row_key"] = o.RowKey
	return toSerialize, nil
}

func (o *RowResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cells",
		"row_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRowResponse := _RowResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRowResponse)

	if err != nil {
		return err
	}

	*o = RowResponse(varRowResponse)

	return err
}

type NullableRowResponse struct {
	value *RowResponse
	isSet bool
}

func (v NullableRowResponse) Get() *RowResponse {
	return v.value
}

func (v *NullableRowResponse) Set(val *RowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRowResponse(val *RowResponse) *NullableRowResponse {
	return &NullableRowResponse{value: val, isSet: true}
}

func (v NullableRowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


