/*
Mezzanine API

Sharded cell-based data store

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mezzanine

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IndexEntryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndexEntryResponse{}

// IndexEntryResponse struct for IndexEntryResponse
type IndexEntryResponse struct {
	// Auto-incremented ID
	AddedId int64 `json:"added_id"`
	Body interface{} `json:"body"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Row key UUID
	RowKey string `json:"row_key"`
	// Shard key UUID
	ShardKey string `json:"shard_key"`
}

type _IndexEntryResponse IndexEntryResponse

// NewIndexEntryResponse instantiates a new IndexEntryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndexEntryResponse(addedId int64, body interface{}, createdAt time.Time, rowKey string, shardKey string) *IndexEntryResponse {
	this := IndexEntryResponse{}
	this.AddedId = addedId
	this.Body = body
	this.CreatedAt = createdAt
	this.RowKey = rowKey
	this.ShardKey = shardKey
	return &this
}

// NewIndexEntryResponseWithDefaults instantiates a new IndexEntryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndexEntryResponseWithDefaults() *IndexEntryResponse {
	this := IndexEntryResponse{}
	return &this
}

// GetAddedId returns the AddedId field value
func (o *IndexEntryResponse) GetAddedId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AddedId
}

// GetAddedIdOk returns a tuple with the AddedId field value
// and a boolean to check if the value has been set.
func (o *IndexEntryResponse) GetAddedIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddedId, true
}

// SetAddedId sets field value
func (o *IndexEntryResponse) SetAddedId(v int64) {
	o.AddedId = v
}

// GetBody returns the Body field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *IndexEntryResponse) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IndexEntryResponse) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *IndexEntryResponse) SetBody(v interface{}) {
	o.Body = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IndexEntryResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IndexEntryResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IndexEntryResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRowKey returns the RowKey field value
func (o *IndexEntryResponse) GetRowKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RowKey
}

// GetRowKeyOk returns a tuple with the RowKey field value
// and a boolean to check if the value has been set.
func (o *IndexEntryResponse) GetRowKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowKey, true
}

// SetRowKey sets field value
func (o *IndexEntryResponse) SetRowKey(v string) {
	o.RowKey = v
}

// GetShardKey returns the ShardKey field value
func (o *IndexEntryResponse) GetShardKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShardKey
}

// GetShardKeyOk returns a tuple with the ShardKey field value
// and a boolean to check if the value has been set.
func (o *IndexEntryResponse) GetShardKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShardKey, true
}

// SetShardKey sets field value
func (o *IndexEntryResponse) SetShardKey(v string) {
	o.ShardKey = v
}

func (o IndexEntryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndexEntryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["added_id"] = o.AddedId
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["row_key"] = o.RowKey
	toSerialize["shard_key"] = o.ShardKey
	return toSerialize, nil
}

func (o *IndexEntryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"added_id",
		"body",
		"created_at",
		"row_key",
		"shard_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndexEntryResponse := _IndexEntryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndexEntryResponse)

	if err != nil {
		return err
	}

	*o = IndexEntryResponse(varIndexEntryResponse)

	return err
}

type NullableIndexEntryResponse struct {
	value *IndexEntryResponse
	isSet bool
}

func (v NullableIndexEntryResponse) Get() *IndexEntryResponse {
	return v.value
}

func (v *NullableIndexEntryResponse) Set(val *IndexEntryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIndexEntryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIndexEntryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndexEntryResponse(val *IndexEntryResponse) *NullableIndexEntryResponse {
	return &NullableIndexEntryResponse{value: val, isSet: true}
}

func (v NullableIndexEntryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndexEntryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


