/*
Mezzanine API

Sharded cell-based data store

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mezzanine

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CellResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CellResponse{}

// CellResponse struct for CellResponse
type CellResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Auto-incremented ID
	AddedId int64 `json:"added_id"`
	Body interface{} `json:"body"`
	// Column name
	ColumnName string `json:"column_name"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Reference key version
	RefKey int64 `json:"ref_key"`
	// Row key UUID
	RowKey string `json:"row_key"`
}

type _CellResponse CellResponse

// NewCellResponse instantiates a new CellResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCellResponse(addedId int64, body interface{}, columnName string, createdAt time.Time, refKey int64, rowKey string) *CellResponse {
	this := CellResponse{}
	this.AddedId = addedId
	this.Body = body
	this.ColumnName = columnName
	this.CreatedAt = createdAt
	this.RefKey = refKey
	this.RowKey = rowKey
	return &this
}

// NewCellResponseWithDefaults instantiates a new CellResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCellResponseWithDefaults() *CellResponse {
	this := CellResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *CellResponse) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CellResponse) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CellResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *CellResponse) SetSchema(v string) {
	o.Schema = &v
}

// GetAddedId returns the AddedId field value
func (o *CellResponse) GetAddedId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AddedId
}

// GetAddedIdOk returns a tuple with the AddedId field value
// and a boolean to check if the value has been set.
func (o *CellResponse) GetAddedIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddedId, true
}

// SetAddedId sets field value
func (o *CellResponse) SetAddedId(v int64) {
	o.AddedId = v
}

// GetBody returns the Body field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CellResponse) GetBody() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CellResponse) GetBodyOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *CellResponse) SetBody(v interface{}) {
	o.Body = v
}

// GetColumnName returns the ColumnName field value
func (o *CellResponse) GetColumnName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ColumnName
}

// GetColumnNameOk returns a tuple with the ColumnName field value
// and a boolean to check if the value has been set.
func (o *CellResponse) GetColumnNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ColumnName, true
}

// SetColumnName sets field value
func (o *CellResponse) SetColumnName(v string) {
	o.ColumnName = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CellResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CellResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CellResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRefKey returns the RefKey field value
func (o *CellResponse) GetRefKey() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RefKey
}

// GetRefKeyOk returns a tuple with the RefKey field value
// and a boolean to check if the value has been set.
func (o *CellResponse) GetRefKeyOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefKey, true
}

// SetRefKey sets field value
func (o *CellResponse) SetRefKey(v int64) {
	o.RefKey = v
}

// GetRowKey returns the RowKey field value
func (o *CellResponse) GetRowKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RowKey
}

// GetRowKeyOk returns a tuple with the RowKey field value
// and a boolean to check if the value has been set.
func (o *CellResponse) GetRowKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RowKey, true
}

// SetRowKey sets field value
func (o *CellResponse) SetRowKey(v string) {
	o.RowKey = v
}

func (o CellResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CellResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["added_id"] = o.AddedId
	if o.Body != nil {
		toSerialize["body"] = o.Body
	}
	toSerialize["column_name"] = o.ColumnName
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["ref_key"] = o.RefKey
	toSerialize["row_key"] = o.RowKey
	return toSerialize, nil
}

func (o *CellResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"added_id",
		"body",
		"column_name",
		"created_at",
		"ref_key",
		"row_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCellResponse := _CellResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCellResponse)

	if err != nil {
		return err
	}

	*o = CellResponse(varCellResponse)

	return err
}

type NullableCellResponse struct {
	value *CellResponse
	isSet bool
}

func (v NullableCellResponse) Get() *CellResponse {
	return v.value
}

func (v *NullableCellResponse) Set(val *CellResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCellResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCellResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCellResponse(val *CellResponse) *NullableCellResponse {
	return &NullableCellResponse{value: val, isSet: true}
}

func (v NullableCellResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCellResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


